version: "3.9"
services:
  warehouse:
    container_name: warehouse-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - POSTGRES_DB=warehouse
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/warehouse
      - SPRING_DATASOURCE_USERNAME=abdelillah
      - SPRING_DATASOURCE_PASSWORD=changemeinprod!
    networks:
      - warehouse
    depends_on:
      - postgres-db


  postgres-db:
    container_name: warehouse-postgres-db
    image: "postgres:15"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "warehouse"
      POSTGRES_USER: "abdelillah"
      POSTGRES_PASSWORD: "changemeinprod!"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - warehouse

networks:
  warehouse:
    driver: bridge

volumes:
  postgres-db:
    driver: local